# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import inventory_pb2 as protos_dot_inventory__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/inventory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InventoryServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReserveItems = channel.unary_unary(
                '/inventory.InventoryService/ReserveItems',
                request_serializer=protos_dot_inventory__pb2.ReserveItemsRequest.SerializeToString,
                response_deserializer=protos_dot_inventory__pb2.ReserveItemsResponse.FromString,
                _registered_method=True)
        self.ReleaseItems = channel.unary_unary(
                '/inventory.InventoryService/ReleaseItems',
                request_serializer=protos_dot_inventory__pb2.ReleaseItemsRequest.SerializeToString,
                response_deserializer=protos_dot_inventory__pb2.ReleaseItemsResponse.FromString,
                _registered_method=True)


class InventoryServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReserveItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReserveItems': grpc.unary_unary_rpc_method_handler(
                    servicer.ReserveItems,
                    request_deserializer=protos_dot_inventory__pb2.ReserveItemsRequest.FromString,
                    response_serializer=protos_dot_inventory__pb2.ReserveItemsResponse.SerializeToString,
            ),
            'ReleaseItems': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseItems,
                    request_deserializer=protos_dot_inventory__pb2.ReleaseItemsRequest.FromString,
                    response_serializer=protos_dot_inventory__pb2.ReleaseItemsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inventory.InventoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inventory.InventoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InventoryService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReserveItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/ReserveItems',
            protos_dot_inventory__pb2.ReserveItemsRequest.SerializeToString,
            protos_dot_inventory__pb2.ReserveItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventory.InventoryService/ReleaseItems',
            protos_dot_inventory__pb2.ReleaseItemsRequest.SerializeToString,
            protos_dot_inventory__pb2.ReleaseItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
