# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/inventory.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16protos/inventory.proto\x12\tinventory\"%\n\x04Item\x12\x0b\n\x03sku\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"G\n\x13ReserveItemsRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\x12\x1e\n\x05items\x18\x02 \x03(\x0b\x32\x0f.inventory.Item\"\\\n\x14ReserveItemsResponse\x12\x16\n\x0ereservation_id\x18\x01 \x01(\t\x12,\n\x06status\x18\x02 \x01(\x0e\x32\x1c.inventory.ReservationStatus\"\'\n\x13ReleaseItemsRequest\x12\x10\n\x08order_id\x18\x01 \x01(\t\"\'\n\x14ReleaseItemsResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08*G\n\x11ReservationStatus\x12\x0c\n\x08RESERVED\x10\x00\x12\x10\n\x0cOUT_OF_STOCK\x10\x01\x12\x12\n\x0eITEM_NOT_FOUND\x10\x02\x32\xb4\x01\n\x10InventoryService\x12O\n\x0cReserveItems\x12\x1e.inventory.ReserveItemsRequest\x1a\x1f.inventory.ReserveItemsResponse\x12O\n\x0cReleaseItems\x12\x1e.inventory.ReleaseItemsRequest\x1a\x1f.inventory.ReleaseItemsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESERVATIONSTATUS']._serialized_start=325
  _globals['_RESERVATIONSTATUS']._serialized_end=396
  _globals['_ITEM']._serialized_start=37
  _globals['_ITEM']._serialized_end=74
  _globals['_RESERVEITEMSREQUEST']._serialized_start=76
  _globals['_RESERVEITEMSREQUEST']._serialized_end=147
  _globals['_RESERVEITEMSRESPONSE']._serialized_start=149
  _globals['_RESERVEITEMSRESPONSE']._serialized_end=241
  _globals['_RELEASEITEMSREQUEST']._serialized_start=243
  _globals['_RELEASEITEMSREQUEST']._serialized_end=282
  _globals['_RELEASEITEMSRESPONSE']._serialized_start=284
  _globals['_RELEASEITEMSRESPONSE']._serialized_end=323
  _globals['_INVENTORYSERVICE']._serialized_start=399
  _globals['_INVENTORYSERVICE']._serialized_end=579
# @@protoc_insertion_point(module_scope)
